set_property PACKAGE_PIN AG14 [get_ports {DDR4_ADR_O[0]}]
set_property PACKAGE_PIN AF17 [get_ports {DDR4_ADR_O[1]}]
set_property PACKAGE_PIN AF15 [get_ports {DDR4_ADR_O[2]}]
set_property PACKAGE_PIN AJ14 [get_ports {DDR4_ADR_O[3]}]
set_property PACKAGE_PIN AD18 [get_ports {DDR4_ADR_O[4]}]
set_property PACKAGE_PIN AG17 [get_ports {DDR4_ADR_O[5]}]
set_property PACKAGE_PIN AE17 [get_ports {DDR4_ADR_O[6]}]
set_property PACKAGE_PIN AK18 [get_ports {DDR4_ADR_O[7]}]
set_property PACKAGE_PIN AD16 [get_ports {DDR4_ADR_O[8]}]
set_property PACKAGE_PIN AH18 [get_ports {DDR4_ADR_O[9]}]
set_property PACKAGE_PIN AD19 [get_ports {DDR4_ADR_O[10]}]
set_property PACKAGE_PIN AD15 [get_ports {DDR4_ADR_O[11]}]
set_property PACKAGE_PIN AH16 [get_ports {DDR4_ADR_O[12]}]
set_property PACKAGE_PIN AL17 [get_ports {DDR4_ADR_O[13]}]
set_property PACKAGE_PIN AL15 [get_ports {DDR4_ADR_O[14]}]
set_property PACKAGE_PIN AL19 [get_ports {DDR4_ADR_O[15]}]
set_property PACKAGE_PIN AM19 [get_ports {DDR4_ADR_O[16]}]

set_property PACKAGE_PIN AG15 [get_ports {DDR4_BA_O[0]}]
set_property PACKAGE_PIN AL18 [get_ports {DDR4_BA_O[1]}]
set_property PACKAGE_PIN AJ15 [get_ports {DDR4_BG_O}]

set_property PACKAGE_PIN AE15 [get_ports {DDR4_CK_C_O}]
set_property PACKAGE_PIN AE16 [get_ports {DDR4_CK_T_O}]
set_property PACKAGE_PIN AE18 [get_ports {DDR4_CS_N_O}]


set_property PACKAGE_PIN AJ16 [get_ports {DDR4_CKE_O}]
set_property PACKAGE_PIN AG19 [get_ports {DDR4_ODT_O}]
set_property PACKAGE_PIN AF18 [get_ports DDR4_ACT_N_O]

set_property PACKAGE_PIN AG16 [get_ports DDR4_RESET_N_O]



set_property PACKAGE_PIN AP34 [get_ports {DDR4_DQS_C_IO[7]}]
set_property PACKAGE_PIN AN34 [get_ports {DDR4_DQS_T_IO[7]}]
set_property PACKAGE_PIN AL32 [get_ports {DDR4_DM_DBI_N_IO[7]}]
set_property PACKAGE_PIN AN31 [get_ports {DDR4_DQ_IO[56]}]
set_property PACKAGE_PIN AL34 [get_ports {DDR4_DQ_IO[57]}]
set_property PACKAGE_PIN AN32 [get_ports {DDR4_DQ_IO[58]}]
set_property PACKAGE_PIN AN33 [get_ports {DDR4_DQ_IO[59]}]
set_property PACKAGE_PIN AM32 [get_ports {DDR4_DQ_IO[60]}]
set_property PACKAGE_PIN AM34 [get_ports {DDR4_DQ_IO[61]}]
set_property PACKAGE_PIN AP31 [get_ports {DDR4_DQ_IO[62]}]
set_property PACKAGE_PIN AP33 [get_ports {DDR4_DQ_IO[63]}]

set_property PACKAGE_PIN AJ33 [get_ports {DDR4_DQS_C_IO[6]}]
set_property PACKAGE_PIN AH33 [get_ports {DDR4_DQS_T_IO[6]}]
set_property PACKAGE_PIN AJ29 [get_ports {DDR4_DM_DBI_N_IO[6]}]
set_property PACKAGE_PIN AK31 [get_ports {DDR4_DQ_IO[48]}]
set_property PACKAGE_PIN AH34 [get_ports {DDR4_DQ_IO[49]}]
set_property PACKAGE_PIN AK32 [get_ports {DDR4_DQ_IO[50]}]
set_property PACKAGE_PIN AJ31 [get_ports {DDR4_DQ_IO[51]}]
set_property PACKAGE_PIN AJ30 [get_ports {DDR4_DQ_IO[52]}]
set_property PACKAGE_PIN AH31 [get_ports {DDR4_DQ_IO[53]}]
set_property PACKAGE_PIN AJ34 [get_ports {DDR4_DQ_IO[54]}]
set_property PACKAGE_PIN AH32 [get_ports {DDR4_DQ_IO[55]}]

set_property PACKAGE_PIN AP30 [get_ports {DDR4_DQS_C_IO[5]}]
set_property PACKAGE_PIN AN29 [get_ports {DDR4_DQS_T_IO[5]}]
set_property PACKAGE_PIN AN26 [get_ports {DDR4_DM_DBI_N_IO[5]}]
set_property PACKAGE_PIN AN28 [get_ports {DDR4_DQ_IO[40]}]
set_property PACKAGE_PIN AM30 [get_ports {DDR4_DQ_IO[41]}]
set_property PACKAGE_PIN AP28 [get_ports {DDR4_DQ_IO[42]}]
set_property PACKAGE_PIN AM29 [get_ports {DDR4_DQ_IO[43]}]
set_property PACKAGE_PIN AN27 [get_ports {DDR4_DQ_IO[44]}]
set_property PACKAGE_PIN AL30 [get_ports {DDR4_DQ_IO[45]}]
set_property PACKAGE_PIN AL29 [get_ports {DDR4_DQ_IO[46]}]
set_property PACKAGE_PIN AP29 [get_ports {DDR4_DQ_IO[47]}]

set_property PACKAGE_PIN AL28 [get_ports {DDR4_DQS_C_IO[4]}]
set_property PACKAGE_PIN AL27 [get_ports {DDR4_DQS_T_IO[4]}]
set_property PACKAGE_PIN AH26 [get_ports {DDR4_DM_DBI_N_IO[4]}]
set_property PACKAGE_PIN AM26 [get_ports {DDR4_DQ_IO[32]}]
set_property PACKAGE_PIN AJ28 [get_ports {DDR4_DQ_IO[33]}]
set_property PACKAGE_PIN AM27 [get_ports {DDR4_DQ_IO[34]}]
set_property PACKAGE_PIN AK28 [get_ports {DDR4_DQ_IO[35]}]
set_property PACKAGE_PIN AH27 [get_ports {DDR4_DQ_IO[36]}]
set_property PACKAGE_PIN AH28 [get_ports {DDR4_DQ_IO[37]}]
set_property PACKAGE_PIN AK26 [get_ports {DDR4_DQ_IO[38]}]
set_property PACKAGE_PIN AK27 [get_ports {DDR4_DQ_IO[39]}]

set_property PACKAGE_PIN AP21 [get_ports {DDR4_DQS_C_IO[3]}]
set_property PACKAGE_PIN AP20 [get_ports {DDR4_DQS_T_IO[3]}]
set_property PACKAGE_PIN AM21 [get_ports {DDR4_DM_DBI_N_IO[3]}]
set_property PACKAGE_PIN AM22 [get_ports {DDR4_DQ_IO[24]}]
set_property PACKAGE_PIN AP24 [get_ports {DDR4_DQ_IO[25]}]
set_property PACKAGE_PIN AN22 [get_ports {DDR4_DQ_IO[26]}]
set_property PACKAGE_PIN AN24 [get_ports {DDR4_DQ_IO[27]}]
set_property PACKAGE_PIN AN23 [get_ports {DDR4_DQ_IO[28]}]
set_property PACKAGE_PIN AP25 [get_ports {DDR4_DQ_IO[29]}]
set_property PACKAGE_PIN AP23 [get_ports {DDR4_DQ_IO[30]}]
set_property PACKAGE_PIN AM24 [get_ports {DDR4_DQ_IO[31]}]

set_property PACKAGE_PIN AK20 [get_ports {DDR4_DQS_C_IO[2]}]
set_property PACKAGE_PIN AJ20 [get_ports {DDR4_DQS_T_IO[2]}]
set_property PACKAGE_PIN AJ21 [get_ports {DDR4_DM_DBI_N_IO[2]}]
set_property PACKAGE_PIN AK22 [get_ports {DDR4_DQ_IO[16]}]
set_property PACKAGE_PIN AL22 [get_ports {DDR4_DQ_IO[17]}]
set_property PACKAGE_PIN AM20 [get_ports {DDR4_DQ_IO[18]}]
set_property PACKAGE_PIN AL23 [get_ports {DDR4_DQ_IO[19]}]
set_property PACKAGE_PIN AK23 [get_ports {DDR4_DQ_IO[20]}]
set_property PACKAGE_PIN AL25 [get_ports {DDR4_DQ_IO[21]}]
set_property PACKAGE_PIN AL20 [get_ports {DDR4_DQ_IO[22]}]
set_property PACKAGE_PIN AL24 [get_ports {DDR4_DQ_IO[23]}]

set_property PACKAGE_PIN AJ25 [get_ports {DDR4_DQS_C_IO[1]}]
set_property PACKAGE_PIN AH24 [get_ports {DDR4_DQS_T_IO[1]}]
set_property PACKAGE_PIN AE25 [get_ports {DDR4_DM_DBI_N_IO[1]}]
set_property PACKAGE_PIN AF24 [get_ports {DDR4_DQ_IO[8]}]
set_property PACKAGE_PIN AJ23 [get_ports {DDR4_DQ_IO[9]}]
set_property PACKAGE_PIN AF23 [get_ports {DDR4_DQ_IO[10]}]
set_property PACKAGE_PIN AH23 [get_ports {DDR4_DQ_IO[11]}]
set_property PACKAGE_PIN AG25 [get_ports {DDR4_DQ_IO[12]}]
set_property PACKAGE_PIN AJ24 [get_ports {DDR4_DQ_IO[13]}]
set_property PACKAGE_PIN AG24 [get_ports {DDR4_DQ_IO[14]}]
set_property PACKAGE_PIN AH22 [get_ports {DDR4_DQ_IO[15]}]

set_property PACKAGE_PIN AH21 [get_ports {DDR4_DQS_C_IO[0]}]
set_property PACKAGE_PIN AG21 [get_ports {DDR4_DQS_T_IO[0]}]
set_property PACKAGE_PIN AD21 [get_ports {DDR4_DM_DBI_N_IO[0]}]
set_property PACKAGE_PIN AE20 [get_ports {DDR4_DQ_IO[0]}]
set_property PACKAGE_PIN AG20 [get_ports {DDR4_DQ_IO[1]}]
set_property PACKAGE_PIN AF20 [get_ports {DDR4_DQ_IO[2]}]
set_property PACKAGE_PIN AE22 [get_ports {DDR4_DQ_IO[3]}]
set_property PACKAGE_PIN AD20 [get_ports {DDR4_DQ_IO[4]}]
set_property PACKAGE_PIN AG22 [get_ports {DDR4_DQ_IO[5]}]
set_property PACKAGE_PIN AF22 [get_ports {DDR4_DQ_IO[6]}]
set_property PACKAGE_PIN AE23 [get_ports {DDR4_DQ_IO[7]}]


set_property PACKAGE_PIN AK17 [get_ports CLK_P_I]


create_clock -period 5.000 [get_ports CLK_P_I]


set_property IOSTANDARD DIFF_SSTL12 [get_ports CLK_P_I]


set_property PACKAGE_PIN K21 [get_ports RST_N_I]
set_property IOSTANDARD LVCMOS18 [get_ports RST_N_I]


set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]